
name: API Test framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
   - cron: 00 18 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      checks: write
      issues: write
      

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Execute Test
      run: mvn clean install
          
    - name: upload a Build Artifact
      if: always()
      uses: actions/download-artifact@v4.1.9
      with:
        name: test-results
        path: 
         test-output/reports/
         target/surefire-reports/
         logs/

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit
    
